import APChemistryPracticeExam from './AP Chemistry Practice Exam.jpg'
import APChemistry2018FRQ from './AP Chemistry 2018 FRQ.jpg'
import RedoxReactions from './Redox Reactions.jpg'
import PrecipitationReactions from './Precipitation Reactions.jpg'
import TypesofChemicalReactions from './Types of Chemical Reactions.jpg'
import Stoichiometry from './Stoichiometry.jpg'
import KineticsReview from './Kinetics Review.jpg'
import ThermodynamicsReview from './Thermodynamics Review.jpg'
import FirstLawofThermodynamics from './First Law of Thermodynamics.jpg'
import SecondLawofThermodynamics from './Second Law of Thermodynamics.jpg'
import ThirdLawofThermodynamics from './Third Law of Thermodynamics.jpg'
import IdentifyingIntermolecularForces from './Identifying Intermolecular Forces .jpg'
import TypesofIntermolecularForces from './Types of Intermolecular Forces.jpg'
import IntermolecularForcesReview from './Intermolecular Forces Review.jpg'
import ChemicalEqualibriumReview from './Chemical Equalibrium Review.jpg'
import EqualibriumConstants from './Equalibrium Constants.jpg'
import LeChateliersPrinciple from './Le Chateliers Principle.jpg'
import AtomicStructureF from './Atomic Structure.jpg'
import SigFigs from './Sig Figs.jpg'
import DimensionalAnalysis from './Dimensional Analysis.jpg'
import PeriodicTrends from './Periodic Trends.jpg'
import AcidsBasesandpH from './Acids Bases and pH .jpg'
import AcidsandBasesIntro from './Acids and Bases Intro.jpg'
import AcidBasePairs from './Acid Base Pairs.jpg'
import TitrationsProblems from './Titrations Problems.jpg'
import ClassifyingIonicorCovalent from './Classifying Ionic or Covalent.jpg'
import NomenclatureWorksheet1and2 from './Nomenclature Worksheet 1 and 2.jpg'
import NomenclatureWorksheet3 from './Nomenclature Worksheet 3.jpg'
import PropertiesofIonicCompounds from './Properties of Ionic Compounds.jpg'
import NomenclatureWorksheet4 from './Nomenclature Worksheet 4.jpg'
import CovalentCompounds from './Covalent Compounds.jpg'
import KineticsPracticeProblems from './Kinetics Practice Problems.jpg'
import KineticsPracticeTest from './Kinetics Practice Test.jpg'

export{
    APChemistryPracticeExam,APChemistry2018FRQ,RedoxReactions,PrecipitationReactions,TypesofChemicalReactions,Stoichiometry,KineticsReview,ThermodynamicsReview,FirstLawofThermodynamics,SecondLawofThermodynamics,ThirdLawofThermodynamics,IdentifyingIntermolecularForces,TypesofIntermolecularForces,IntermolecularForcesReview,ChemicalEqualibriumReview,EqualibriumConstants,LeChateliersPrinciple,AtomicStructureF,SigFigs,DimensionalAnalysis,PeriodicTrends,AcidsBasesandpH,AcidsandBasesIntro,AcidBasePairs,TitrationsProblems,ClassifyingIonicorCovalent,NomenclatureWorksheet1and2,NomenclatureWorksheet3,PropertiesofIonicCompounds,NomenclatureWorksheet4,CovalentCompounds,KineticsPracticeProblems,KineticsPracticeTest
}